# Generated by Django 6.0.1 on 2026-01-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
